### ISSUE TITLE
put versions newer than 4.0.7a as releases 

### ISSUE THREAD

**Issue by Goldman1337** [nod-dev/VenturePlan#12]
the last version that's noted as a release is 4.0.7a, so WowUp is not finding 4.0.8 for update

**Comment by lozengenods** [comment]
Not the owner of this repo, but WowUp added the author's site directly to the latest beta version. [Issue #620](https://github.com/WowUp/WowUp/issues/620)

You can now just search Venture Plan in the regular search and keep it updated directly from the author.

**Comment by Goldman1337** [comment]
Awesome, thanks!
